const TeamData = [
  {
    id: 1,
    position: "Wissenschaftl. Projektkoordination",
    people: [
      {
        id: 1,
        name: "Dr. Ferréol Berendt",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        phone: "+49 3334 657 414",
        email: "Ferreol.Berendt[at]hnee.de",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-Ferr%C3%A9ol.png?raw=true",
        page: "https://www.hnee.de/de/Fachbereiche/Wald-und-Umwelt/Lehrbeauftragte-/-wissenschaftliche-Mitarbeiter/-innen/Ferrol-Berendt-E10529.htm",
      },
    ],
  },
  {
    id: 2,
    position: "Nachwuchsgruppe",
    people: [
      {
        id: 1,
        name: "Tobias Bender",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        phone: "+49 3334 657 276",
        email: "Tobias.Bender[at]hnee.de",
        image: "",
        page: "",
      },
      {
        id: 2,
        name: "Ramazan Bülbül",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        phone: "",
        email: "Ramazan.Buelbuel[at]hnee.de",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-Ramazan.jpg?raw=true",
        page: "https://www.linkedin.com/in/ramazan-b%C3%BClb%C3%BCl-03798394/?originalSubdomain=de",
      },
      {
        id: 3,
        name: "Maximilian Jakob",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        phone: "",
        email: "Maximilian.Jakob[at]hnee.de",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-Max.jpg?raw=true",
        page: "",
      },
      {
        id: 4,
        name: "Dr. Julia Kaplick",
        address: "Landeskompetenzzentrum Forst Eberswalde",
        phone: "+49 3334 2759 473",
        email: "Julia.Kaplick[at]lfb.brandenburg.de",
        image: "",
        page: "",
      },
      {
        id: 5,
        name: "Tina Krüger",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        phone: "",
        email: "Tina.Krueger[at]hnee.de",
        page: "",
      },
      {
        id: 6,
        name: "Alexa Michel",
        address: "Thünen-Institut für Waldökosysteme",
        phone: "+49 3334 3820 367",
        email: "Alexa.Michel[at]thuenen.de",
        page: "https://www.thuenen.de/de/fachinstitute/waldoekosysteme/personal/wissenschaftliches-personal/alexa-michel",
      },
      {
        id: 7,
        name: "Stephan Playfair",
        address: "Leibniz-Zentrum für Agrarlandschaftsforschung (ZALF) e.V.",
        phone: "",
        email: "Stephan.Playfair[at]zalf.de",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-Playfair.jpg?raw=true",
        page: "https://www.linkedin.com/in/spwr/?trk=public_profile_browsemap&originalSubdomain=de",
      },
      {
        id: 8,
        name: "Dr. Friedrich Reppe",
        address: "Max-Planck-Institut für Kolloid- und Grenzflächenforschung",
        phone: "+49 331 567 9249",
        email: "Friedrich.Reppe[at]mpikg.mpg.de",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-Friedrich.jpg?raw=true",
        page: "https://www.mpikg.mpg.de/person/51211",
      },
    ],
  },

  {
    id: 3,
    position: "Gesamtprojektleitung",
    people: [
      {
        id: 1,
        name: "Prof. Dr. Tobias Cremer",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde",
        image:
          "https://github.com/FBerendt/wald-reallabor-photo/blob/main/team-TobiasCremer.jpg?raw=true",
        page: "https://www.hnee.de/de/Fachbereiche/Wald-und-Umwelt/Professorinnen-und-Professoren/Tobias-Cremer/Prof.-Dr.-Tobias-Cremer-E6856.htm",
      },
    ],
  },
  {
    id: 4,
    position: "Teilprojektleitung",
    people: [
      {
        id: 1,
        name: "Prof. Dr. Jan-Peter Mund",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde (HNEE)",
        // phone: "+49 3334 657 189",
        // email: "Jan-Peter.Mund(at)hnee.de",
        image: "",
        page: "https://www.hnee.de/en/Faculties/Faculty-of-Forest-and-Environment/Professors/Jan-Peter-Mund/Prof.-Dr.-Jan-Peter-Mund-E5173.htm",
      },
      {
        id: 2,
        name: "Prof. Dr. Alexander Pfriem",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde (HNEE)",
        // phone: "+49 3334 657 377",
        // email: "Alexander.Pfriem(at)hnee.de",
        image: "",
        page: "https://www.hnee.de/de/Fachbereiche/Holzingenieurwesen/Team/Professorinnen/Prof.-Dr.-Ing.-Alexander-Pfriem/Prof.-Dr.-Ing.-Alexander-Pfriem-E7615.htm",
      },
      {
        id: 3,
        name: "Prof. Dr. Ulrich Schwarz",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde (HNEE)",
        // phone: "+49 3334 657 374",
        // email: "Ulrich.Schwarz(at)hnee.de",
        image: "",
        page: "https://www.hnee.de/de/Fachbereiche/Holzingenieurwesen/Team/Professorinnen/Prof.-Dr.-Ing.-Ulrich-Schwarz/Prof.-Dr.-Ing.-Ulrich-Schwarz-E7614.htm",
      },
      {
        id: 4,
        name: "Prof. Dr. Peter Spathelf",
        address: "Hochschule für nachhaltige Entwicklung Eberswalde (HNEE)",
        // phone: "+49 3334 657 171",
        // email: "Peter.Spathelf(at)hnee.de",
        image: "",
        page: "https://www.hnee.de/de/Fachbereiche/Wald-und-Umwelt/Professorinnen-und-Professoren/Peter-Spathelf/Prof.-Dr.-Peter-Spathelf-E3235.htm",
      },
      {
        id: 5,
        name: "Prof. Dr.-Ing. Karola Dierichs",
        address:
          "Max-Planck-Institut für Kolloid- und Grenzflächenforschung (MPIKG)",
        // phone: " +49 3315 679 452",
        // email: "karola.dierichs(at)mpikg.mpg.de",
        image: "",
        page: "https://www.mpikg.mpg.de/person/110913",
      },
      {
        id: 6,
        name: "Dr. Tanja Sanders",
        address: "Thünen-Institut für Waldökosysteme",
        // phone: "+49 3334 3820 339",
        // email: "tanja.sanders(at)thuenen.de",
        image: "",
        page: "https://www.thuenen.de/de/fachinstitute/waldoekosysteme/personal/wissenschaftliches-personal/dr-tanja-sanders",
      },
      {
        id: 7,
        name: "Dr. Ulrike Hagemann",
        address: "Leiterin Landeskompetenzzentrum Eberswalde (LFE)",
        // phone: "+49 3334 2759 400",
        // email: "ulrike.hagemann(at)lfb.brandenburg.de",
        image: "",
        page: "https://forst.brandenburg.de/lfb/de/ueber-uns/landeskompetenzzentrum-lfe/leiterin-lfe/#",
      },
      {
        id: 8,
        name: "Prof. Dr. Jens Schröder",
        address: "Landeskompetenzzentrum Forst Eberswalde (LFE)",
        // phone: "+49 3334 657 359",
        // email: "jens.schroeder(at)hnee.de",
        image: "",
        page: "https://www.hnee.de/de/Fachbereiche/Wald-und-Umwelt/Professorinnen-und-Professoren/Dr.-Jens-Schrder/Prof.-Dr.-Jens-Schrder-E10035.htm",
      },
      {
        id: 9,
        name: "Prof. Dr. Gunnar Lischeid",
        address: "Leibniz-Zentrum für Agrarlandschaftsforschung (ZALF)",
        // phone: "+49 3343 282 250",
        // email: "lischeid(at)zalf.de",
        image: "",
        page: "https://www.zalf.de/de/ueber_uns/mitarbeiter/Seiten/lischeid_g.aspx",
      },
      {
        id: 10,
        name: "Dr. Michaela Eder",
        address:
          "Max-Planck-Institut für Kolloid- und Grenzflächenforschung (MPIKG)",
        // phone: "+49 3315 679 422",
        // email: "michaela.eder[at]mpikg.mpg.de",
        image: "",
        page: "https://www.mpikg.mpg.de/person/22188",
      },
    ],
  },
];
export default TeamData;
